apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000 # Specify the NodePort you want to use (e.g., 30000)
  selector:
    app: guestbook-ui
  type: NodePort # Change the type from LoadBalancer to NodePort
